### ISSUE TITLE
Support for Python3

### ISSUE THREAD

**Issue by ChandrPr** [qd-cae/qd-eng#2]
Hi,
I was just looking for a module like yours, to read dyna D3PLOT files. However, I noticed you mentioned support for Python2. I was just wondering if it would be possible to also support Python3? I am not sure how complicated it will be, given Python3's stricter limitations on using str for ascii/binary.

Thanks!
Praphulla

**Comment by qd-codie** [comment]
Give me a few days

**Comment by qd-codie** [comment]
I think I can compile it for Python3.5 and higher, but I have not found any way to do it with FEMZIP support on Windows, since there are no compatible link libraries for Visual Studio 15. Is that ok for you or do you have any more specifics (before I start working on it)?

**Comment by ChandrPr** [comment]
FEMZIP support is not needed for me. That should be fine. Thanks!

**Comment by qd-codie** [comment]
It's already almost done, just error handling needs to be fixed.

**Comment by qd-codie** [comment]
Windows python3.5 wheel is uploaded, but Binout reading is still buggy in that version. D3plot is working fine though. I will do the Linux wheels these days too ...

**Comment by qd-codie** [comment]
It's done. See the changelog in the Readme for restrictions though.
