### ISSUE TITLE
Abaqus Support

### ISSUE THREAD

**Issue by qd-codie** [qd-cae/qd-eng#3]
Support reading of abaqus result files. This will be difficult ...

**Comment by ChandrPr** [comment]
Abaqus already has a python tool (abaqus python) for reading their odb files. Unfortunately, it is some type of proprietary python distribution that requires abaqus licences. Having an open source version would be great!

**Comment by qd-codie** [comment]
Yeah a friend of mine requested this for a very long time. I don't like licensing when accessing my data, since the data is mine and I want access to it all the time without having to pay. Not sure though how to do it appropriately.

**Comment by ChandrPr** [comment]
Their manual does not offer any details (like lstc does). Their scripting manual shows how to use their API (in python and C), but doesn't explain how the data is formatted in the odb file. To be honest, I don't think their customer support will be too helpful on that front either (anything to make people buy their licences). You will probably have to reverse-engineer their data structure. But first, no harm in trying to talk to them.

**Comment by qd-codie** [comment]
Yeah he knew that there was a python interface, but probably not that it does not use any license (also I did not know). I'm sure I can somehow interface their libraries, but did not succeed in a first attempt. I will keep an eye on it, but will close this topic for now.
