### ISSUE TITLE
Bug in class qd.cae.dyna.Binout()

### ISSUE THREAD

**Issue by Jdahn** [qd-cae/qd-eng#7]
Hi, 

I trying to read out forces in a node where boundary conditions are applied. My post processor lists the forces just fine, i guess the error is on the qd.cae.dyna.Binout() side.

Code i've tried:
```

from qd.cae.dyna import Binout

Results = Binout("Base_Model_One_El_Tens_V1_1mm.key.binout")
bnd    = Results.read("bndout")
bndout = Results.read("bndout",'nodes')
node1 = Results.read("bndout",'1')
print(bnd)
print(bndout)
print(node1) 
```

Results in:

```
['nodes']
[]
[]
```

**Comment by qd-codie** [comment]
Hmm might be a bug. Can you send me an example file? Unfortunately I have no one lying around with bndout. Most probably that's the reason, why I messed up this output type.

**Comment by Jdahn** [comment]
I've uploaded the file here: https://ufile.io/oqk17
Thanks!

**Comment by qd-codie** [comment]
Hmmm yeah I think I found the issue and will fix it later. The depth of the directory was deeper than expected.

**Comment by qd-codie** [comment]
You can update to 0.5.5 with:

`python -m pip install qd --upgrade`

The bug should be fixed.
